name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Run ESLint
        run: npm run lint

  test-changed:
    runs-on: ubuntu-latest
    needs: lint
    outputs:
      ran: ${{ steps.run-changed.outputs.ran }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      - name: Get changed spec files
        id: changed
        uses: tj-actions/changed-files@v45
        with:
          files: |
            cypress/e2e/**/*.cy.js

      - name: Run only changed specs (or skip)
        id: run-changed
        run: |
          if [ -z "${{ steps.changed.outputs.all_changed_files }}" ]; then
            echo "No spec changes. Skipping tests."
            echo "ran=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          SPECS=$(echo "${{ steps.changed.outputs.all_changed_files }}" | tr ' ' ',')
          echo "Running: $SPECS"
          npx cypress run --spec "$SPECS"
          echo "ran=true" >> $GITHUB_OUTPUT

      - name: List mochawesome JSONs
        if: steps.run-changed.outputs.ran == 'true'
        run: |
          echo "Listing cypress/reports directory:"
          ls -la cypress/reports || true
          echo "Listing JSONs:"
          ls -la cypress/reports/.jsons || true

      - name: Build HTML report (robust merge)
        if: steps.run-changed.outputs.ran == 'true'
        run: |
          set -e
          mkdir -p report
          echo "Listing cypress/reports recursively:"
          ls -la cypress/reports || true
          find cypress/reports -type f -name "*.json" -print || true

          JSONS="$(ls cypress/reports/.jsons/*.json 2>/dev/null || true) $(ls cypress/reports/*.json 2>/dev/null || true)"
          echo "Found JSONs: $JSONS"

          if [ -z "$JSONS" ]; then
            echo "No mochawesome JSONs found → creating fallback report/index.html"
            cat > report/index.html <<'HTML'
            <!doctype html>
            <html>
              <head><meta charset="utf-8"><title>Cypress Report</title></head>
              <body>
                <h1>Cypress Report</h1>
                <p>No mochawesome JSONs found. Check reporter config or test logs.</p>
              </body>
            </html>
            HTML
          else
            npx mochawesome-merge $JSONS > report/merged.json
            npx marge report/merged.json -f index -o report
            echo "Listing report/:"
            ls -la report
          fi

      - name: Upload Pages artifact (report/)
        if: steps.run-changed.outputs.ran == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: report

  deploy-pages:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: test-changed
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
